module example1
#
# NB: this file was automatically generated by Dynare
#     from example1.mod
#

using DynareModel
using DynareOptions
using DynareOutput

using Utils
using SteadyState

using example1Static
using example1Dynamic
if isfile("example1SteadyState.jl")
    using example1SteadyState
end
if isfile("example1SteadyState2.jl")
    using example1SteadyState2
end

export model_, options_, oo_

oo_ = dynare_output()
oo_.dynare_version = "4.5-unstable"

options_ = dynare_options()
options_.dynare_version = "4.5-unstable"

model_ = dynare_model()
model_.fname = "example1"
model_.dynare_version = "4.5-unstable"
model_.sigma_e = zeros(Float64, 2, 2)
model_.correlation_matrix = ones(Float64, 2, 2)
model_.orig_eq_nbr = 6
model_.eq_nbr = 6
model_.ramsey_eq_nbr = 0
model_.h = zeros(Float64, 1, 1)
model_.correlation_matrix_me = ones(Float64, 1, 1)
# Endogenous Variables
model_.endo = [
              DynareModel.Endo("y", "y", "y")
              DynareModel.Endo("c", "c", "c")
              DynareModel.Endo("k", "k", "k")
              DynareModel.Endo("a", "a", "a")
              DynareModel.Endo("h", "h", "h")
              DynareModel.Endo("b", "b", "b")
             ]
# Exogenous Variables
model_.exo = [
             DynareModel.Exo("e", "e", "e")
             DynareModel.Exo("u", "u", "u")
            ]
# Parameters
model_.param = [
               DynareModel.Param("beta", "beta", "beta")
               DynareModel.Param("rho", "rho", "rho")
               DynareModel.Param("alpha", "alpha", "alpha")
               DynareModel.Param("delta", "delta", "delta")
               DynareModel.Param("theta", "theta", "theta")
               DynareModel.Param("psi", "psi", "psi")
               DynareModel.Param("tau", "tau", "tau")
              ]
model_.orig_endo_nbr = 6
model_.lead_lag_incidence = [
 0 4 10;
 0 5 11;
 1 6 0;
 2 7 0;
 0 8 0;
 3 9 12;]';
model_.nstatic = 1;
model_.nfwrd   = 2;
model_.npred   = 2;
model_.nboth   = 1;
model_.nsfwrd   = 3;
model_.nspred   = 3;
model_.ndynamic   = 5;
model_.equation_tags = [
                      ]
model_.static_and_dynamic_models_differ = false;
model_.exo_names_orig_ord = collect(1:2);
model_.maximum_lag = 1;
model_.maximum_lead = 1;
model_.maximum_endo_lag = 1;
model_.maximum_endo_lead = 1;
oo_.steady_state = zeros(6)
model_.maximum_exo_lag = 0;
model_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(2)
model_.params = fill(NaN, 7)
model_.nnzderivatives = [26; 48; -1];
model_.params[ 3 ] = 0.36
model_.params[ 2 ] = 0.95
model_.params[ 7 ] = 0.025
model_.params[ 1 ] = 0.99
model_.params[ 4 ] = 0.025
model_.params[ 6 ] = 0
model_.params[ 5 ] = 2.95
model_.static = example1Static.static!
model_.dynamic = example1Dynamic.dynamic!
if isfile("example1SteadyState.jl")
    model_.user_written_analytical_steady_state = true
    model_.steady_state = example1SteadyState.steady_state!
end
if isfile("example1SteadyState2.jl")
    model_.analytical_steady_state = true
    model_.steady_state = example1SteadyState2.steady_state!
end
if isfile("example1StaticParamsDerivs.jl")
    using example1StaticParamsDerivs
    model_.static_params_derivs = example1StaticParamsDerivs.params_derivs
end
if isfile("example1DynamicParamsDerivs.jl")
    using example1DynamicParamsDerivs
    model_.dynamic_params_derivs = example1DynamicParamsDerivs.params_derivs
end
end
